#!/bin/bash

# Load configuration
source ./rpi-arch-sdprep.conf || echo "[err] missing config file, this won't work..."

# Set up pacman and install packages for ansible
pacman-key --init
pacman-key --populate
pacman-key --refresh-keys
pacman -S sudo python --needed --noconfirm

# Set hostname
echo "${host_name}" > "/etc/hostname"

# Set sudoers file
echo "# Generated by installer script" > "/etc/sudoers"
echo "root ALL=(ALL) ALL" >> "/etc/sudoers"
echo "%wheel ALL=(ALL) ALL" >> "/etc/sudoers"
echo "%ansible ALL=(ALL) NOPASSWD:ALL" >> "/etc/sudoers"

# Create default user account
useradd --create-home --user-group --system \
        --uid "${default_user_uid}" \
        --comment "${default_user_comment}" \
        "${default_user_name}"

# Write authorized_key for default user
sudo "${default_user_name}" mkdir ~/.ssh
sudo "${default_user_name}" echo "${default_user_authorized_key}" > ~/.ssh/authorized_keys

# Disable root's and default user's password login
passwd -l "root"
passwd -l "${default_user_name}"

## Reboot
#reboot