#!/bin/bash

# Ask to continue
echo "Press enter to start post install script or Ctrl+C to abort..."
read

# Load configuration
source ./rpi-arch-sdprep.conf || echo "[err] missing config file, this won't work..."

# Set up pacman and install packages for ansible
pacman-key --init
pacman-key --populate
pacman-key --refresh-keys
pacman -S sudo python --needed --noconfirm

# Set sudoers file
echo "# Generated by installer script" > "/etc/sudoers"
echo "root ALL=(ALL) ALL" >> "/etc/sudoers"
echo "%wheel ALL=(ALL) ALL" >> "/etc/sudoers"
echo "%ansible ALL=(ALL) NOPASSWD:ALL" >> "/etc/sudoers"

# Create default user account
useradd --create-home --user-group --system \
        --uid "${default_user_uid}" \
        --comment "${default_user_comment}" \
        "${default_user_name}"

# Write authorized_key for default user
mkdir "/home/${default_user_name}/.ssh"
echo "${default_user_authorized_key}" > "/home/${default_user_name}/.ssh/authorized_keys"
chown "${default_user_name}:${default_user_name}" "/home/${default_user_name}/.ssh" -R
chmod 0700 "/home/${default_user_name}/.ssh" -R

# Disable root's and default user's password login
passwd -l "root"
passwd -l "${default_user_name}"
userdel --remove alarm

# Reboot
reboot